id: I4B99CCFC
legacy_id: P004147
ocr_import_info:
  bdrc_scan_id: W30179
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T05:47:16'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:24:11.647019+00:00'
last_modified: 2022-09-03 19:24:20.342267
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30179
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW30179
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དགའ་ལྡན་བྱང་རྩེའི་དབུ་མའི་ཡིག་ཆ།
  author: སྒོམ་སྡེ་བ་ནམ་མཁའ་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9049183733229126
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG401:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG401
      total_pages: 777
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG401.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9049183733229126
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
