id: P004147
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:56:20.232643
source_metadata:
  id: bdr:W30179
  title: དགའ་ལྡན་བྱང་རྩེའི་དབུ་མའི་ཡིག་ཆ།
  author: ''
  volumes:
    50a0d6528dfa4e71bd0fe91f607fbcca:
      image_group_id: I1KG401
      title: ''
      volume_number: 1
      total_pages: 777
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
